version: "3"

services:
  front:
      build:
        context: ./todoclient
        dockerfile: Dockerfile
      volumes:
        - ./todoclient:/app
      ports:
        - "8080:8080"
      image: todoclient
      container_name: todoclient
      networks:
        - todoApp
      depends_on:
        - backend 
  backend:
      build:
        context: ./todoserver
        dockerfile: Dockerfile
      volumes:
        - ./todoserver:/app/src
      ports:
        - "5000:5500"
      image: todoserver
      container_name: todoserver
      networks:
        - todoApp
networks:
  todoApp:
volumes:
  web-root:
    driver: local
  node_modules:
