version: "3"

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./src:/app/src
      ports:
        - "5500:5500"
      container_name: todoserver
      networks:
        - todoApp
networks: